[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""

[conda]
symbol = "🅒 "
format = "via [$symbol$environment](bold green) "
ignore_base = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
# Use custom format
format = """
[┌──────────────────>](bold green)
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
# trim_at = ".companyname.com"
disabled = false


[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"


[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[status]
style = "bg:blue"
symbol = "💣 "
format = '[\[$symbol$status\]]($style) '
disabled = false

